name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test14:
    name: Test 1.14
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v1

      - name: actions-setup-redis
        uses: shogo82148/actions-setup-redis@v1.0.1

      - name: Run Unit tests.
        env:
          DISABLE_SAVER_TEST: Y
        run: go test -short -coverprofile coverage.txt

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt

  test13:
    name: Test 1.13
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: actions-setup-redis
        uses: shogo82148/actions-setup-redis@v1.0.1

      - name: Run Unit tests.
        env:
          DISABLE_SAVER_TEST: Y
        run: go test -short -coverprofile coverage.txt

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
#
#  test12:
#    name: Test 1.12
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.12
#
#      - name: Check out code
#        uses: actions/checkout@v1
#
#      - name: Run Unit tests.
#        run: go test -short -coverprofile coverage.txt
#
#      - name: Upload Coverage report to CodeCov
#        uses: codecov/codecov-action@v1.0.0
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          file: ./coverage.txt
#
#  test11:
#    name: Test 1.11
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.11
#
#      - name: Check out code
#        uses: actions/checkout@v1
#
#      - name: Run Unit tests.
#        run: go test -short -coverprofile coverage.txt
#
#      - name: Upload Coverage report to CodeCov
#        uses: codecov/codecov-action@v1.0.0
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          file: ./coverage.txt
